import os
from contextlib import contextmanager


class Settings:
    """Process-wide settings shared by the Xsuite packages.

    Available settings and their equivalent environment variables are:

    ``print_mode`` — ``XSUITE_PRINT_MODE``
        Values: ``print`` (default), ``suppress``
        Controls informational output produced by Xsuite.

    ``progress_indicator`` — ``XSUITE_PROGRESS_INDICATOR``
        Values: ``tqdm`` (default), ``text``, ``suppress``
        Selects how progress is displayed when printing is enabled.

    ``allow_kernel_compilation`` — ``XSUITE_ALLOW_KERNEL_COMPILATION``
        Values: ``False`` (default), ``True``
        Allows compilation when no compatible prebuilt kernel is available.

    ``force_kernel_compilation`` — ``XSUITE_FORCE_KERNEL_COMPILATION``
        Values: ``False`` (default), ``True``
        Always compiles kernels and skips prebuilt-kernel lookup. Intended
        primarily for Xsuite development and debugging.

    ``show_kernel_diagnostics`` — ``XSUITE_SHOW_KERNEL_DIAGNOSTICS``
        Values: ``False`` (default), ``True``
        During prebuilt-kernel selection, reports why each candidate kernel is
        selected or rejected.

    ``cffi_forbid_compile`` — ``XSUITE_CFFI_FORBID_COMPILE``
        Values: ``False`` (default), ``True``
        Prevents CFFI from compiling CPU kernels. Used primarily for debugging
        and testing.

    ``cffi_keep_build_files`` — ``XSUITE_CFFI_KEEP_BUILD_FILES``
        Values: ``False`` (default), ``True``
        Keeps the intermediate files generated by CFFI. Used primarily for
        debugging and testing.

    ``cuda_backend`` — ``XSUITE_CUDA_BACKEND``
        Values: ``nvrtc`` (default), ``clang``
        Selects the compiler backend used for CUDA kernels.

    ``cuda_fast_compile`` — ``XSUITE_CUDA_FAST_COMPILE``
        Values: ``True`` (default), ``False``
        Enables faster NVRTC compilation when supported.

    ``cuda_compiler`` — ``XSUITE_CUDA_COMPILER``
        Values: ``None`` (default), executable path
        Selects the clang++ executable used by the CUDA clang backend.

    Notes
    -----
    The same object is exposed as ``xobjects.settings`` and
    ``xtrack.settings``. Environment variables provide its initial values when
    Xobjects is imported. Later Python assignments take precedence and can be
    applied temporarily with :meth:`override`.

    Boolean environment variables accept ``1``/``0``, ``true``/``false``,
    ``yes``/``no``, and ``on``/``off``, case-insensitively.

    ``force_kernel_compilation=True`` skips prebuilt-kernel lookup and takes
    precedence over ``allow_kernel_compilation``. When forcing is disabled,
    ``allow_kernel_compilation=True`` permits compilation only if a compatible
    prebuilt kernel is unavailable. Compilation can also be enabled for one
    context or element class by setting its ``allow_kernel_compilation``
    attribute to ``True``. The legacy class attribute
    ``allow_no_prebuilt_kernel`` is temporarily recognized for compatibility
    with packages that have not migrated yet.

    Examples
    --------
    Allow Xsuite to compile a kernel when no compatible prebuilt kernel is
    available:

    >>> import xtrack as xt
    >>> xt.settings.allow_kernel_compilation = True

    Equivalently, set ``XSUITE_ALLOW_KERNEL_COMPILATION=1`` before starting
    Python.

    Settings can also be overridden temporarily; their previous values are
    restored when leaving the context:

    >>> xt.settings.print_mode = 'print'
    >>> with xt.settings.override(print_mode='suppress'):
    ...     print(xt.settings.print_mode)  # suppress
    >>> print(xt.settings.print_mode)  # print
    """

    def __init__(self):
        object.__setattr__(self, '_definitions', {})
        object.__setattr__(self, '_values', {})

    def _register(
        self,
        name,
        *,
        default,
        environment_variable=None,
        choices=None,
        environment_parser=None,
        value_type=None,
    ):
        if name in self._definitions:
            raise ValueError(f'Setting {name!r} is already registered.')

        definition = {
            'environment_variable': environment_variable,
            'choices': choices,
            'value_type': value_type,
        }
        self._definitions[name] = definition

        value = default
        if (environment_variable is not None
                and environment_variable in os.environ):
            environment_value = os.environ[environment_variable]
            try:
                value = (environment_parser(environment_value)
                         if environment_parser else environment_value)
            except (TypeError, ValueError) as err:
                raise ValueError(
                    f'Invalid value for '
                    f'{self._setting_description(name, definition)}: '
                    f'{err}') from err
        self._set(name, value)

    def _set(self, name, value):
        try:
            definition = self._definitions[name]
        except KeyError as err:
            raise AttributeError(f'Unknown Xsuite setting {name!r}.') from err

        choices = definition['choices']
        value_type = definition['value_type']
        setting_description = self._setting_description(name, definition)
        if value_type is not None and not isinstance(value, value_type):
            raise TypeError(
                f'Invalid value {value!r} for {setting_description}; '
                f'expected {self._type_name(value_type)}.')
        if choices is not None and value not in choices:
            expected = ', '.join(repr(choice) for choice in choices)
            raise ValueError(
                f'Invalid value {value!r} for {setting_description}; '
                f'expected one of {expected}.')

        self._values[name] = value

    def __getattr__(self, name):
        try:
            return self._values[name]
        except KeyError as err:
            raise AttributeError(f'Unknown Xsuite setting {name!r}.') from err

    def __setattr__(self, name, value):
        self._set(name, value)

    @contextmanager
    def override(self, **kwargs):
        """Temporarily override settings and restore them on exit."""
        previous = {}
        for name, value in kwargs.items():
            if name not in self._definitions:
                raise AttributeError(f'Unknown Xsuite setting {name!r}.')
            previous[name] = getattr(self, name)

        # Validate every value before changing any setting.
        for name, value in kwargs.items():
            definition = self._definitions[name]
            setting_description = self._setting_description(name, definition)
            value_type = definition['value_type']
            if value_type is not None and not isinstance(value, value_type):
                raise TypeError(
                    f'Invalid value {value!r} for {setting_description}; '
                    f'expected {self._type_name(value_type)}.')
            choices = definition['choices']
            if choices is not None and value not in choices:
                expected = ', '.join(repr(choice) for choice in choices)
                raise ValueError(
                    f'Invalid value {value!r} for {setting_description}; '
                    f'expected one of {expected}.')

        try:
            for name, value in kwargs.items():
                self._set(name, value)
            yield self
        finally:
            for name, value in previous.items():
                self._set(name, value)

    def __repr__(self):
        values = ', '.join(
            f'{name}={getattr(self, name)!r}' for name in self._values)
        return f'Settings({values})'

    def __dir__(self):
        return sorted(set(super().__dir__()) | set(self._definitions))

    @staticmethod
    def _type_name(value_type):
        if isinstance(value_type, tuple):
            return ' or '.join(tt.__name__ for tt in value_type)
        return value_type.__name__

    @staticmethod
    def _setting_description(name, definition):
        description = f'Python setting xobjects.settings.{name}'
        environment_variable = definition['environment_variable']
        if environment_variable is not None:
            description += (
                f' or equivalently the environment variable '
                f'{environment_variable}'
            )
        return description


def _parse_boolean(value):
    normalized = value.strip().lower()
    if normalized in ('1', 'true', 'yes', 'on'):
        return True
    if normalized in ('0', 'false', 'no', 'off'):
        return False
    raise ValueError(
        f'Invalid boolean value {value!r}; expected one of 1, 0, true, '
        'false, yes, no, on, or off.')


def _parse_choice(value):
    return value.strip().lower()


def _parse_optional_string(value):
    value = value.strip()
    return value if value else None


settings = Settings()
settings._register(
    'print_mode',
    default='print',
    environment_variable='XSUITE_PRINT_MODE',
    choices=('print', 'suppress'),
    environment_parser=_parse_choice,
)
settings._register(
    'progress_indicator',
    default='tqdm',
    environment_variable='XSUITE_PROGRESS_INDICATOR',
    choices=('tqdm', 'text', 'suppress'),
    environment_parser=_parse_choice,
)
settings._register(
    'allow_kernel_compilation',
    default=False,
    environment_variable='XSUITE_ALLOW_KERNEL_COMPILATION',
    choices=(False, True),
    environment_parser=_parse_boolean,
    value_type=bool,
)
settings._register(
    'force_kernel_compilation',
    default=False,
    environment_variable='XSUITE_FORCE_KERNEL_COMPILATION',
    choices=(False, True),
    environment_parser=_parse_boolean,
    value_type=bool,
)
settings._register(
    'show_kernel_diagnostics',
    default=False,
    environment_variable='XSUITE_SHOW_KERNEL_DIAGNOSTICS',
    choices=(False, True),
    environment_parser=_parse_boolean,
    value_type=bool,
)
settings._register(
    'cffi_forbid_compile',
    default=False,
    environment_variable='XSUITE_CFFI_FORBID_COMPILE',
    choices=(False, True),
    environment_parser=_parse_boolean,
    value_type=bool,
)
settings._register(
    'cffi_keep_build_files',
    default=False,
    environment_variable='XSUITE_CFFI_KEEP_BUILD_FILES',
    choices=(False, True),
    environment_parser=_parse_boolean,
    value_type=bool,
)
settings._register(
    'cuda_backend',
    default='nvrtc',
    environment_variable='XSUITE_CUDA_BACKEND',
    choices=('nvrtc', 'clang'),
    environment_parser=_parse_choice,
)
settings._register(
    'cuda_fast_compile',
    default=True,
    environment_variable='XSUITE_CUDA_FAST_COMPILE',
    choices=(False, True),
    environment_parser=_parse_boolean,
    value_type=bool,
)
settings._register(
    'cuda_compiler',
    default=None,
    environment_variable='XSUITE_CUDA_COMPILER',
    environment_parser=_parse_optional_string,
    value_type=(str, type(None)),
)
